/*
* generated by Xtext
*/
package tadp.examples.ui.contentassist;

import tadp.examples.ui.contentassist.AbstractMappingProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MappingProposalProvider extends AbstractMappingProposalProvider {

}
