/*
 * generated by Xtext
 */
package tadp.examples;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MappingRuntimeModule extends tadp.examples.AbstractMappingRuntimeModule {

}
