/*
 * generated by Xtext
 */
package tadp.examples.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MappingUiModule extends tadp.examples.ui.AbstractMappingUiModule {
	public MappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
