/*
* generated by Xtext
*/
package tadp.examples.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MappingTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
