
/*
 * generated by Xtext
 */
 
package tadp.examples.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return tadp.examples.ui.internal.MappingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return tadp.examples.ui.internal.MappingActivator.getInstance().getInjector("tadp.examples.Mapping");
	}
	
}
